backend:
  name: github
  repo: GSA/SaferFederalWorkforce.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: vNext

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Key Area
    name: Key Areas
    folder: _key-areas/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Permalink', name: 'permalink', widget: 'string', default: '/keyareas/MYFOLDER/'}
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'areanav'}
      - {label: 'Type', name: 'type', widget: 'hidden', default: 'safetyarea'}
      - {label: 'Category', name: 'category', widget: 'hidden', default: 'Key Areas'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Lead", name: "lead", widget: "string"}
      - {
          label: "Revised Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
