name: a11y

on: [pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install jekyll dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install dependencies
        run: npm install

      - name: Start up jekyll server
        run: bundle exec jekyll serve --detach

      - name: Test accessibility
        run: "npm run test-a11y"
